### ISSUE TITLE
사용자는 다른 사용자의 방명록 Home 화면을 볼 수 있다.

### ISSUE THREAD

**Issue by 3o14** [Footprint-meow/Footprint-FrontEnd#29]
## 🚧 Description
방명록 Home 화면 guest ver 

## ✅ Todo
- [x] 방명록 이미지 삽입
- [x] 헤더 UI
- [x] 나머지 UI 구현
- [x] 방명록 타이틀 컴포넌트 임포트하기
- [x] 호스트 인삿말 정렬하기

## 🛠️Etc
// 참고한 블로그나 깨달은 점 등 삽질 내용을 기록해주세요
