### ISSUE TITLE
사용자는 해당 방명록에 대한 발자국과 사진을 확인할 수 있다.

### ISSUE THREAD

**Issue by hyun812** [Footprint-meow/Footprint-FrontEnd#46]
## 🚧 Description
사용자는 해당 방명록에 대한 발자국과 사진을 확인할 수 있다.

## ✅ Todo
- [ ] 발자국 조회 api
- [ ] 사진 조회 api
- [ ] 읽음 처리 api
- [ ] 비밀글 UI구현

## 🛠️Etc
// 참고한 블로그나 깨달은 점 등 삽질 내용을 기록해주세요
